// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhbpkwabhmxxstudxezc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoYnBrd2FiaG14eHN0dWR4ZXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTExOTIsImV4cCI6MjA2NDM2NzE5Mn0.nCgZbv_dDgkOpYIKC1Ypd3zny5jC3Nzy_gF7XDUJbHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);